taggedwikitest/urls.py
from django.conf.urls.defaults import *
from taggedwiki.views import viewListAllSpaces

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^taggedwikitest/', include('taggedwikitest.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^taggedwiki/', include('taggedwiki.urls')),

    (r'^$', viewListAllSpaces),
)

taggedwikitest/taggedwiki/views.py
#Copyright (C) 2009 James (james at jarofgreen dot co dot uk)
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Lesser General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.#
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Lesser General Public License for more details.
#
#You should have received a copy of the GNU Lesser General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from taggedwiki.models import *
from django.template import RequestContext
from django import forms
from django import template
from cgi import escape
from random import randint
import re
import taggedwiki.decorators as decorators
 
def viewListAllSpaces(request):
	return render_to_response('allSpaces.html',{'spaces':Space.objects.all(),},context_instance=RequestContext(request))

@decorators.loadSpaceOr404
def viewListSpace(request,space):
	return render_to_response('space.html',{'space':space,},context_instance=RequestContext(request))

@decorators.loadSpaceOr404
def viewListPagesWithTagAjax(request, space, tagname):
	try:
		tag = Tag.objects.get(Title=tagname)
	except Tag.DoesNotExist:
		raise Http404()
	pages = Page.objects.filter(Space=space,Tags=tag)
	return render_to_response('pageList.html',{'pages':pages,},context_instance=RequestContext(request))

@decorators.loadSpaceOr404
@decorators.loadPageOr404
def viewPage(request,space,page):
	outPages = []
	tags = Tag.objects.filter(page__Space=space).distinct()
	# get body, escape for html
	body = " "+escape(page.Body).replace("\n","<br/>")+" " # extra spaces are so tags at start and end are matched
	# pass 1: for every tag we find in our body, store the first position it occurs (if it does) and add to outPages, counting links as we go
	for tag in tags:
		tag.LocationInBody = -1
		regex = escape(tag.Title).replace('\\','\\\\').replace('.','\\.').replace('^','\\^').replace('$','\\$').replace('*','\\*').replace('+','\\+').replace('{','\\{').replace('[','\\[').replace(']','\\]').replace('|','\\|').replace('(','\\(').replace(')','\\)') # escaping all special chars in a regular expression		
		regexObj = re.compile('\W'+regex+'\W' , re.IGNORECASE)
		regexMatch = regexObj.search( body )
		if regexMatch:
			tag.CountInBody = len ( regexObj.findall(body) ) # TODO: This will undercount if tags are right next to each other with only one character seperating them.
			for outPage in Page.objects.filter(Space=space, Tags=tag):
				if not outPage == page:
					if not outPage in outPages:
						outPage.NumberOfLinks = tag.CountInBody
						outPages.append(outPage)
					else:
						outPageIndex = outPages.index(outPage)
						outPages[outPageIndex].NumberOfLinks = outPages[outPageIndex].NumberOfLinks + tag.CountInBody
			tag.LocationInBody = regexMatch.start()+1
	# pass 2: Now put in HTML for each tag
	tags = sorted([t for t in tags if t.LocationInBody > -1], key=lambda obj: obj.LocationInBody)
	offset = 0
	for tag in tags:
		html = '<span class="tag" title="'+escape(tag.Title, True)+'"></span>'
		body = body[0:tag.LocationInBody+offset]+html+body[tag.LocationInBody+offset:]
		offset = offset + len(html)
	# finally sort results before returning
	outPages = sorted([p for p in outPages], key=lambda obj: obj.NumberOfLinks, reverse=True)
	return render_to_response('viewPage.html',{'space':space,'page':page,'outPages':outPages,'body':body,'tags':tags},context_instance=RequestContext(request))

class EditPageForm(forms.Form):
	Title = forms.CharField(required=True)
	Body = forms.CharField(widget=forms.Textarea,required=True)
	AddANewTag = forms.CharField(widget=forms.Textarea,required=False)

@decorators.loadSpaceOr404
@decorators.loadPageOr404
def viewEditPage(request,space,page):
	if request.method == 'POST':
		form = EditPageForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			page.Title = cd['Title'].strip()
			page.Body = cd['Body']
			page.LastUpdateIP = request.META['REMOTE_ADDR']
			page.save()
			for newtag in cd['AddANewTag'].split("\n"):
				if newtag.strip():
					page.addTag(newtag.strip())
			for removetag in request.POST.getlist('Remove'):
				tag = Tag.objects.get(id=removetag)
				if tag in page.Tags.all():
					page.removeTag(tag)
			return HttpResponseRedirect(page.get_absolute_url())
	else:
		form = EditPageForm(  {  'Title':page.Title, 'Body':page.Body, }  )
	return render_to_response('editPage.html', {'space':space,'page':page,'form': form,},context_instance=RequestContext(request))

@decorators.loadSpaceOr404
def viewNewPage(request,space):
	if request.method == 'POST':
		form = EditPageForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			# todo: check name doesn't already exist!
			page = Page(Space=space, Title=cd['Title'], Body=cd['Body'], LastUpdateIP = request.META['REMOTE_ADDR'])
			page.save()
			for newtag in cd['AddANewTag'].split("\n"):
				if newtag.strip():
					page.addTag(newtag.strip())
			return HttpResponseRedirect(page.get_absolute_url())
	else:
		form = EditPageForm( )
	return render_to_response('editPage.html', {'space':space,'form': form,},context_instance=RequestContext(request))

templates/allSpaces.html
{% extends "base.html" %}

{% block title %}Spaces{% endblock %}
{% block browserTitle %}Spaces{% endblock %}

{% block content %}
	<ul>
		{% for space in spaces %}<li><a href="{{ space.get_absolute_url }}">{{ space.Title }}</a> {{ space.Description }}</li>{% endfor %}
	</ul>
{% endblock %}

templates/base.html
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<title>{% block browserTitle %}{% endblock %} - TaggedWiki</title>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.3/prototype.js"></script>
		<style type="text/css">
			body, html {
				margin: 0px;
				padding: 0px;
				text-align: center;
				font-family: arial, sans-serif;
			}
			#title {
				padding: 10px 0px;
				width:100%;
				background: #6f8;
				background-repeat: repeat-x;
				border-bottom: solid 2px #6fa;
			}
			#content {
				text-align: left;
				padding: 0px;
				background: #FFF;
				width:100%;
				font-size: 10pt;
			}
			#text {
				padding: 5px;
				margin-top: 20px;
				margin-bottom: 40px;
				margin-left: auto;
				margin-right: auto;
				width: 80%;
			}
			h1 {
				font-weight: bold;
				font-size: 20pt;
				color: #fff;
			}
			textarea#id_Body { width: 100%; height: 400px;	}
			textarea#id_AddANewTag { width: 400px; height: 50px;	}
			#footer {
				clear: both;
				text-align: right;
				font-size: 80%; 
				font-style: italic;
			}
			div.pageContents span.tag {
				border: 4px solid #6f8;
			}
		</style>
	</head>
	<body onload="{% block onbodyload %}{% endblock %}">

	<div id="content">

		<div id="title"><div style="padding: 20px"><h1>{% block title %}TaggedWiki{% endblock %}</h1></div></div>

		<div id="text">{% block content %}Content{% endblock %}</div>
		<div id="footer">
			<a href="http://github.com/jarofgreen/TaggedWiki/tree/master">TaggedWiki is open source</a>
		</div>

	</div>

</body>
</html>

templates/editPage.html
{% extends "base.html" %}

{% block title %}{{ space.Title }}/{{ page.Title }}{% endblock %}
{% block browserTitle %}{{ space.Title }}/{{ page.Title }}{% endblock %}

{% block content %}
	<form action="" method="post">
		<table width="100%">
			{{ form.as_table }}
			<tr><td>Click To Remove an existing tag</td>
				<td>
					{% for tag in page.Tags.all %}
						<input type="checkbox" name="Remove" value="{{ tag.id }}" id="RemoveTag{{ tag.id }}">
						<label for="RemoveTag{{ tag.id }}">{{ tag.Title }}</label><br/>
					{% endfor %}
				</td></tr>
		</table>
		<input type="submit" value="Submit">
    </form>

{% endblock %}

templates/newPage.html
{% extends "base.html" %}

{% block title %}{{ space.Title }}/ New page{% endblock %}
{% block browserTitle %}{{ space.Title }}/ New page{% endblock %}

{% block content %}
	<form action="" method="post">
		<table width="100%">
			{{ form.as_table }}
		</table>
		<input type="submit" value="Submit">
    </form>

{% endblock %}

templates/pageList.html
<ul>
{% for page in pages %}
<li><a href="{{ page.get_absolute_url }}">{{ page.Title }}</a></li>
{% endfor %}
</ul>

templates/space.html
{% extends "base.html" %}

{% block title %}{{ space.Title }}{% endblock %}
{% block browserTitle %}{{ space.Title }}{% endblock %}

{% block content %}
	<ul>
		{% for page in space.pages.all %}<li><a href="{{ page.get_absolute_url }}">{{ page.Title }}</a></li>{% endfor %}
		<li><a href="{{ space.get_absolute_new_page_url }}"><em>New Page</em></a></li>
	</ul>
{% endblock %}

templates/viewPage.html
{% extends "base.html" %}

{% block title %}<a href="{{ space.get_absolute_url }}">{{ space.Title }}</a>/{{ page.Title }}{% endblock %}
{% block browserTitle %}{{ space.Title }}/{{ page.Title }}{% endblock %}

{% block content %}
	<div style="float: right; width: 20%; border: 1px solid #6f8; padding: 10px;">
		{% for outPage in outPages %}<a href="{{ outPage.get_absolute_url }}">{{ outPage.Title }} ({{ outPage.NumberOfLinks }})</a><br/>{% endfor %}
		<p/>[<a href="{{ page.get_absolute_edit_url }}">Edit This Page</a>] Last edited {{ page.LastUpdated|timesince}} ago by {{ page.LastUpdateIP }}<p/>
	</div>

	<em  style="color:#999;"><strong>Tags:</strong> {% for tag in page.Tags.all %}{{ tag.Title }}, {% endfor %}</em><p/>

	<div id="pageContents" class="pageContents">{{ body|safe }}</div><p/>

	<em  style="color:#999;"><strong>Tags Found In This Page:</strong> {% for tag in tags %}{{ tag.Title }} ({{ tag.CountInBody }}), {% endfor %}</em><p/>


	<script>
		function makeTagsClickable() {
			var l = $('pageContents').childElements();
			for (var i = (l.length-1); i >= 0; i--) {
				if(l[i].hasClassName('tag')) {
					Event.observe(l[i], 'click', tagClicked);
				}
			}	
		}

		function tagClicked() {
			var newContainer = new Element('div');
			$('pageContents').insert(newContainer);
			newContainer.absolutize();
			newContainer.clonePosition(this, {'offsetLeft':10,'offsetTop':10});
			newContainer.style.width = '300px';
			newContainer.style.height = '200px';
			var b = new Element('span').update("Close");
			newContainer.insert(b);
			Event.observe(b, 'click', closeTags);
			var a = new Element('span').update("Loading");
			newContainer.insert(a);
			newContainer.style.background = 'white';
			newContainer.style.border = '#6fa 2px solid';
			new Ajax.Updater(a, '{{ space.get_absolute_url }}t/'+encodeURIComponent(this.title)+'/ajax/');
		}
		function closeTags() {
			this.up().remove();
		}
	</script>

{% endblock %}

{% block onbodyload %}makeTagsClickable();{% endblock %}